version: '2'
services:
  mqtt:
    image: localhost/mosquitto-tls
      #networks:
      #- backend-net
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
    environment:
      - DOMAIN=frippe.com
      - EMAIL=frippe@frippe.com
    volumes:
      - ./mosquitto/conf/:/mosquitto/conf:Z
      - ./mosquitto/log/:/mosquitto/log:Z
      - ./letsencrypt:/etc/letsencrypt:Z
        #- ./scripts:/scripts
    container_name: mqtt-tls
    restart: always
#networks:
#  backend-net:
#    external:
#      name: backend-net
